backend:
  name: github
  repo: LovroHodak/jure
  branch: main
  #change the name of repo to yours

media_folder: "public/images"
public_folder: "images"

collections:
  - name: info
    label: Info
    files:
      - file: src/content/meta.json
        name: meta
        label: 'Meta'
        fields:
          - name: title
            label: 'Title'
            widget: string
            required: true